include(CheckIncludeFiles)

check_include_files("dlfcn.h"       HAVE_DLFCN_H)
check_include_files("inttypes.h"    HAVE_INTTYPES_H)
check_include_files("memory.h"      HAVE_MEMORY_H)
check_include_files("stdint.h"      HAVE_STDINT_H)
check_include_files("stdlib.h"      HAVE_STDLIB_H)
check_include_files("strings.h"     HAVE_STRINGS_H)
check_include_files("string.h"      HAVE_STRING_H)
check_include_files("sys/stat.h"    HAVE_SYS_STAT_H)
check_include_files("sys/types.h"   HAVE_SYS_TYPES_H)
check_include_files("unistd.h"      HAVE_UNISTD_H)

include(CheckTypeSize)

check_type_size("int"           SIZEOF_INT)
check_type_size("int16_t"       SIZEOF_INT16_T)
check_type_size("int32_t"       SIZEOF_INT32_T)
check_type_size("int64_t"       SIZEOF_INT64_T)
check_type_size("long"          SIZEOF_LONG)
check_type_size("long long"     SIZEOF_LONG_LONG)
check_type_size("short"         SIZEOF_SHORT)
check_type_size("uint16_t"      SIZEOF_UINT16_T)
check_type_size("uint32_t"      SIZEOF_UINT32_T)
check_type_size("u_int16_t"     SIZEOF_U_INT16_T)
check_type_size("u_int32_t"     SIZEOF_U_INT32_T)

set(HAVE_INT ${HAVE_SIZEOF_INT})
set(HAVE_INT16_T ${HAVE_SIZEOF_INT16_T})
set(HAVE_INT32_T ${HAVE_SIZEOF_INT32_T})
set(HAVE_INT64_T ${HAVE_SIZEOF_INT64_T})
set(HAVE_LONG ${HAVE_SIZEOF_LONG})
set(HAVE_LONG_LONG ${HAVE_SIZEOF_LONG})
set(HAVE_SHORT ${HAVE_SIZEOF_SHORT})
set(HAVE_UINT16_T ${HAVE_SIZEOF_UINT16_T})
set(HAVE_UINT32_T ${HAVE_SIZEOF_UINT32_T})
set(HAVE_U_INT16_T ${HAVE_SIZEOF_U_INT16_T})
set(HAVE_U_INT32_T ${HAVE_SIZEOF_U_INT32_T})

if (ANDROID)
    set(SIZE16 "short")
    set(USIZE16 "unsigned short")
    set(SIZE32 "int") 
    set(USIZE32 "unsigned int")
    set(SIZE64 "long long")
endif()
